### ISSUE TITLE
посилання  на  чат не  працюе

### ISSUE THREAD

**Issue by leon-mbs** [VSydorenko/prro_docs#1]
ЦIкао  було  би  взнати чому  iснують  два  протоколи  взаемодii з  ДПС якI  оп  сутI роблять  те  саме

**Comment by VSydorenko** [comment]
> ЦIкао  було  би  взнати чому  iснують  два  протоколи  взаемодii з  ДПС якI  оп  сутI роблять  те  саме

Це всім цікаво. Один був раніше, він же використовується в "залізних" РРО.
Інший був розроблений спеціально для ПРРО.

Посилання поміняю, тут актуальне: https://t.me/+dYYTlWr5-8JjOTIy

**Comment by leon-mbs** [comment]
ну в  залiзгних то  понятно там  ЭЦП не  накладеш
У  мене  проект -  реалiзацшя для API    тIльки з  офлайн  сесiями  пока непонятно  якось  мутно  описано - таке  вражання  що з залiзного перетягнули 
а  ще  незрозумIло  на фIга  z-звiти для програмного  рро- там же  та сама  iнфа що  в  чеках
податкова  сама  не може  до  купи  скласти чи що

дякую за  дiнк
