### ISSUE TITLE
А чому не можна розділити приклади відкритя зміни для оффлайну і онлайну?

### ISSUE THREAD

**Issue by arcnext** [VSydorenko/prro_docs#6]
я можу помилятись але 
`
<ORDERTAXNUM>101234567890123</ORDERTAXNUM>`

Вказуеться тільки коли оффлайн чек

Булоб круто якщо було би два приклади чека відкриття зміни

**Comment by VSydorenko** [comment]
Мені здається, ви очікуєте більшого, ніж я можу вам дати.

Я в цьому проекті просто скопіював документацію із портала податкової, перевів його з ворда в мд формат і прикріпив приклади - щоб все було в одному місці з можливістю перегляду історії зміни документації.

Тому, виправляти щось в цій документації, можна сказати, немає особливого сенсу, якщо тільки ви не заливаєте нову редакцію із сайту податкової. Та і відповідати на питання, чому так, а не інакше, я не можу - ці механізми такі, які є і я їх змінювати не можу ніяк.

Зайдіть в Телеграм групу (посилання є на головній сторінці), в ній періодично приходять люди, що безпосередньо з цим працюють на стороні податкової - можливо, вони зреагують на ваші прохання і щось змінять, але це зовсім не обов'язково.
